default:
  image: python:3.13
  # 3-alpine --> no git
  # 3-slim -->  no git
  tags:
    - inasset

stages:
  - test
  - build
  - deploy

cache:
  key: cache-default
  paths:
    - .cache/pip
    - .cache/pipx
    - .cache/pre-commit

# TODO: move templates here to keep dependency direction clear
#       (even if the code is not involved here, we might want to make
#       clear that wjs-profile depends on wjs-submission)
include:
  - project: 'wjs/wjs-profile-project'
    ref: wjs-production
    file: '.gitlab-ci-pkg-build-and-upload.yml'
  - project: 'wjs/wjs-profile-project'
    ref: wjs-production
    file: '.gitlab-ci-pkg-deploy.yml'
  - project: 'wjs/wjs-profile-project'
    ref: ${CI_COMMIT_REF_NAME}
    file: '.gitlab-ci-run-tests.yml'
  - project: 'wjs/wjs-profile-project'
    ref: ${CI_COMMIT_REF_NAME}
    file: '.gitlab-ci-pre-commit.yml'


run-tests:
  # Always run tests, except for tags, which have tests already run on
  # them when the commit is made.
  except:
    - tags
  extends:
    - .run-tests


pre-commit:
  # Always run linting, except for tags
  except:
    - tags
  extends:
    - .run-pre-commit


upload-package:
  only:
    - tags
  extends:
    - .upload-package


deploy-to-dev:
  extends:
    - .deploy
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  variables:
    SERVER_IP: "$TEST_SERVER_IP"
    SERVER_USER: "$TEST_SERVER_USER"
    DEPLOY_CMD: "deploy-dev-wjs-submission:${CI_COMMIT_SHA}"
    # TODO: the deploy script does not yet know about "deploy-dev-wjs-submission"!
