default:
  image: python:3.13
  # 3-alpine --> no git
  # 3-slim -->  no git
  tags:
    - inasset

stages:
  - test
  - build
  - deploy

cache:
  key: cache-default
  paths:
    - .cache/pip
    - .cache/pipx
    - .cache/pre-commit

# TODO: move templates here to keep dependency direction clear
#       (even if the code is not involved here, we might want to make
#       clear that wjs-profile depends on wjs-submission)
include:
  - project: 'wjs/wjs-profile-project'
    ref: wjs-production
    file: '.gitlab-ci-pkg-build-and-upload.yml'
  - project: 'wjs/wjs-profile-project'
    ref: wjs-production
    file: '.gitlab-ci-pkg-deploy.yml'
  - project: 'wjs/wjs-profile-project'
    ref: wjs-production
    file: '.gitlab-ci-run-tests.yml'
  - project: 'wjs/wjs-profile-project'
    ref: wjs-production
    file: '.gitlab-ci-pre-commit.yml'


run-tests:
  # Always run tests, except for tags, which have tests already run on
  # them when the commit is made.
  except:
    - tags
  # Not extending wjs-profile test job because the pytest command line is different
  # extends:
  #   - .run-tests

  tags:
    - fast-test
  stage: test
  image: registry.gitlab.sissamedialab.it/wjs/janeway/debian-python-git-janeway:${JANEWAY_VERSION}

  # NB: Must match with test_settings.DATABASES
  variables:
    JANEWAY_VERSION: "production"
    POSTGRES_USER: janeway
    POSTGRES_PASSWORD: janeway
    POSTGRES_DB: janeway
    # used by `pytest ...`:
    DJANGO_SETTINGS_MODULE: core.cicd_test_settings
    # used by `manage.py ...`:
    JANEWAY_SETTINGS_MODULE: core.cicd_settings
    # Use the following after force-pushes:
    GIT_STRATEGY: clone
    # see e.g.:
    # - https://docs.gitlab.com/ee/ci/runners/configure_runners.html#git-strategy
    # - https://stackoverflow.com/a/66519431/1581629
    PYTHONPATH: ${CI_PROJECT_DIR}

  services:
    - name: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/postgres:13.8
      alias: db
      command: [
        "postgres",
        "-c", "max_locks_per_transaction=2048"
      ]

  script:
    - cp setup_environment /usr/local/bin/
    - setup_environment
    - cd /janeway/src
    - pytest ${CI_PROJECT_DIR}/ -v -n 6 --create-db




pre-commit:
  # Always run linting, except for tags
  except:
    - tags
  extends:
    - .run-pre-commit




upload-package:
  only:
    - tags
  extends:
    - .upload-package




deploy-to-pre-production:
  extends:
    - .deploy
  environment: pre-production
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $CI_COMMIT_REF_NAME == "wjs-production"
      when: on_success
    - when: manual
  allow_failure: true
  variables:
    SERVER_IP: "$TEST_SERVER_IP"
    SERVER_USER: "$TEST_SERVER_USER"
    DEPLOY_CMD: "deploy-pp-wjs-submission"


deploy-to-test:
  # Deploy the current commit to test instance
  # Warning! Be sure not to disrupt other peoples work 🙂
  extends:
    - .deploy
  environment: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - when: manual
  allow_failure: true
  variables:
    SERVER_IP: "$TEST_SERVER_IP"
    SERVER_USER: "$TEST_SERVER_USER"
    DEPLOY_CMD: "deploy-test-wjs-submission:${CI_COMMIT_SHA}"


deploy-to-dev:
  extends:
    - .deploy
  environment: dev
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $CI_COMMIT_REF_NAME == "wjs-develop"
      when: on_success
    - when: manual
  allow_failure: true
  variables:
    SERVER_IP: "$TEST_SERVER_IP"
    SERVER_USER: "$TEST_SERVER_USER"
    DEPLOY_CMD: "deploy-dev-wjs-submission:${CI_COMMIT_SHA}"


deploy-to-production:
  extends:
    - .deploy
  environment: production
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - when: manual
  allow_failure: true
  variables:
    SERVER_IP: "$PROD_SERVER_IP"
    SERVER_USER: "$PROD_SERVER_USER"
    DEPLOY_CMD: "deploy-prod-wjs-submission"
