[metadata]
name = wjs-submission
version = 2.0.0.dev1
description = Janeway plugin to manage submissions for WJS
author = Matteo Gamboz
author_email = gamboz@medialab.sissa.it
license = AGPL-3.0-or-later
long_description = file: README.md
long_description_content_type = text/markdown; charset=UTF-8
url = https://gitlab.sissamedialab.it/wjs/wjs-submission-project
platforms = any

# https://pypi.org/classifiers/
classifiers =
    Environment :: Web Environment
    Framework :: Django
    Intended Audience :: Developers
    Operating System :: OS Independent
    Programming Language :: Python
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3 :: Only
    Topic :: Internet :: WWW/HTTP
    Topic :: Internet :: WWW/HTTP :: Dynamic Content


[options]
packages = find_namespace:
include_package_data = True
install_requires =
    redis
    django-redis
    django-bootstrap5 ~= 25.2
    defusedxml
    wjs-themes >= 1.0.6.dev6
    wjs-user-search >= 2.0.0.dev1
    django-q2
    channels
    channels-redis

[options.extras_require]
test =
# pytest == 8.3.3  # temporary workaround for wjs-profile-project#204
    pytest-django
    pytest-mock
    pytest-freezegun
    pytest-xdist
    pytest-reverse

[options.packages.find]
include = wjs*

[options.package_data]
* =
    *.html
    *.css
    *.woff
    *.woff2
    *.js
    *.scss
    *.po
    *.mo
    *.png
    *.json
    *.pdf
    *.tar.gz
