[metadata]
name = wjs_submission
version = 0.0.1
description = Janeway plugin to manage submissions for WJS
author = Matteo Gamboz
author_email = gamboz@medialab.sissa.it
license = AGPL-3.0-or-later
long_description = file: README.md
long_description_content_type = text/markdown; charset=UTF-8
url = https://gitlab.sissamedialab.it/wjs/wjs-profile-project
platforms = any

# https://pypi.org/classifiers/
classifiers =
    Environment :: Web Environment
    Framework :: Django
    Intended Audience :: Developers
    Operating System :: OS Independent
    Programming Language :: Python
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3 :: Only
    Topic :: Internet :: WWW/HTTP
    Topic :: Internet :: WWW/HTTP :: Dynamic Content


[options]
packages = find_namespace:
include_package_data = True

[options.extras_require]
test =
     # pytest == 8.3.3  # temporary workaround for wjs-profile-project#204
     pytest-django
     pytest-mock
     pytest-freezegun
     pytest-xdist
     pytest-reverse
