# Generated by Django 4.2.20 on 2025-07-09 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("submission", "0081_auto_20240927_1021"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleSubmission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "article",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submission_data",
                        to="submission.article",
                        verbose_name="Article",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article submission",
                "verbose_name_plural": "Articles submission",
            },
        ),
    ]
