# Generated by Django 4.2.23 on 2025-07-20 22:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wjs_submission", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlesubmission",
            name="arxiv_category",
            field=models.CharField(blank=True, max_length=30, default="", verbose_name="Arxiv category"),
        ),
    ]
