# Generated by Django 4.2.23 on 2025-07-23 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0099_alter_accountrole_options"),
        ("wjs_submission", "0002_articlesubmission_arxiv_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlesubmission",
            name="cover_letter_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cover_letter_file",
                to="core.file",
            ),
        ),
    ]
