# Generated by Django 4.2.23 on 2025-09-17 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0099_alter_accountrole_options"),
        ("submission", "0089_keyword_created_keyword_deactivated_keyword_notes_and_more"),
        ("wjs_submission", "0003_articlesubmission_cover_letter_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlesubmission",
            name="affiliation_country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.country",
                verbose_name="Affiliation country",
            ),
        ),
        migrations.CreateModel(
            name="Collaboration",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("institutional_email", models.EmailField(blank=True, max_length=254, help_text="If available")),
                ("address", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "public_listing",
                    models.BooleanField(
                        default=False,
                        help_text="If set, this collaboration is visible in the selection list",
                        verbose_name="Approved for public listing",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        help_text="The account that created this collaboration",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_collaborations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "linked_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="The account automatically added to the authors list when a collaboration is added",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="linked_collaborations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        help_text="Logo representing this collaboration",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.file",
                    ),
                ),
            ],
            options={
                "verbose_name": "Collaboration",
                "verbose_name_plural": "Collaborations",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="ArticleCollaboration",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "relation",
                    models.CharField(
                        choices=[
                            ("by", "by a collaboration"),
                            ("on_behalf_of", "on behalf of a collaboration"),
                            ("none", "No collaboration involved"),
                        ],
                        default="by",
                        help_text="Indicates whether the article was written by or on behalf of the collaboration",
                        max_length=32,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order of this collaboration in the author/collaboration list"
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collaborations",
                        to="submission.article",
                    ),
                ),
                (
                    "collaboration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to="wjs_submission.collaboration",
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
                "unique_together": {("article", "collaboration")},
            },
        ),
    ]
