# Generated by Django 4.2.23 on 2025-10-01 19:59

from django.db import migrations


def force_copyright_label_type(apps, schema_editor):
    Setting = apps.get_model("core", "Setting")
    # The original setting type it's `mini-html` but we need richer text (ie: links)
    Setting.objects.filter(name="copyright_submission_label").update(types="rich-text")


class Migration(migrations.Migration):
    dependencies = [
        ("wjs_submission", "0004_articlesubmission_affiliation_country_collaboration_and_more"),
    ]

    operations = [migrations.RunPython(force_copyright_label_type, migrations.RunPython.noop)]
