# Generated by Django 4.2.23 on 2025-09-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "wjs_submission",
            "0005_copyright_label_type",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="articlesubmission",
            name="administrative_files",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="administrative_files",
                to="core.file",
            ),
        ),
        migrations.AddField(
            model_name="articlesubmission",
            name="cas",
            field=models.CharField(
                choices=[
                    (
                        "no",
                        "My article has no associated code or the code will not be deposited",
                    ),
                    (
                        "esm",
                        "My article has code included as electronic supplementary material",
                    ),
                    ("url", "My article has associated code in a data repository"),
                ],
                default="",
                max_length=255,
                verbose_name="CAS declaration",
            ),
        ),
        migrations.AddField(
            model_name="articlesubmission",
            name="cas_url",
            field=models.URLField(default="", verbose_name="CAS URL"),
        ),
        migrations.AddField(
            model_name="articlesubmission",
            name="das",
            field=models.CharField(
                choices=[
                    (
                        "no",
                        "My article has no associated data or the data will not be deposited",
                    ),
                    (
                        "esm",
                        "My article has data included as electronic supplementary material",
                    ),
                    ("url", "My article has associated data in a data repository"),
                ],
                default="",
                max_length=255,
                verbose_name="DAS declaration",
            ),
        ),
        migrations.AddField(
            model_name="articlesubmission",
            name="das_url",
            field=models.URLField(default="", verbose_name="DAS URL"),
        ),
    ]
