# Generated by Django 4.2.23 on 2025-10-12 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0066_issue_type_bleach_20240507_1359"),
        ("wjs_submission", "0006_articlesubmission_administrative_files_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessMode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("code", models.SlugField(max_length=255, verbose_name="Code")),
                (
                    "user_selectable",
                    models.BooleanField(verbose_name="User selectable", default=True),
                ),
            ],
            options={
                "verbose_name": "Access mode",
                "verbose_name_plural": "Access modes",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="AccessModeJournal",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "access_mode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameters",
                        to="wjs_submission.accessmode",
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_mode_parameters",
                        to="journal.journal",
                    ),
                ),
                (
                    "copyright",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Copyright declaration",
                    ),
                ),
                (
                    "licence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_mode_parameters",
                        to="submission.licence",
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal / Access mode connection",
                "verbose_name_plural": "Journal / Access mode connections",
            },
        ),
        migrations.AddField(
            model_name="articlesubmission",
            name="access_mode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="wjs_submission.accessmode",
            ),
        ),
        migrations.AddField(
            model_name="articlesubmission",
            name="special_request",
            field=models.TextField(verbose_name="Special request", blank=True),
        ),
    ]
