# Generated by Django 4.2.23 on 2025-10-12 13:27

from django.db import migrations
from plugins.wjs_submission.data import create_access_mode


class Migration(migrations.Migration):
    dependencies = [
        ("wjs_submission", "0007_accessmode_accessmodejournal_and_more"),
    ]

    operations = [migrations.RunPython(create_access_mode, migrations.RunPython.noop)]
