# Generated by Django 4.2.25 on 2025-11-24 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wjs_submission", "0008_define_access_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlesubmission",
            name="special_request",
            field=models.TextField(blank=True, default="", verbose_name="Special request"),
        ),
        migrations.CreateModel(
            name="RevisionStorage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    models.JSONField(blank=True, default=dict, verbose_name="Draft data"),
                ),
                (
                    "article",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="submission.article",
                    ),
                ),
            ],
            options={
                "verbose_name": "Draft article",
                "verbose_name_plural": "Draft articles",
            },
        ),
    ]
