# Generated by Django 4.2.25 on 2025-12-15 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wjs_submission", "0009_alter_articlesubmission_special_request_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="revisionstorage",
            name="revision_step",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Current revision step"),
        ),
        migrations.AddField(
            model_name="revisionstorage",
            name="revision_flow_type",
            field=models.CharField(
                choices=[
                    ("confirm", "Confirmation of previous version"),
                    ("metadata", "Metadata change"),
                    ("full", "Revision submission"),
                ],
                default="full",
                max_length=10,
                verbose_name="Revision flow type",
            ),
            preserve_default=False,
        ),
    ]
