# Generated by Django 4.2.25 on 2025-12-17 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wjs_submission", "0010_revisionstorage_revistion_step_revisionstorage_stage"),
    ]

    operations = [
        migrations.CreateModel(
            name="RevisionArticleAuthorOrder",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "author",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
                (
                    "revision_storage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="wjs_submission.revisionstorage"
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
            },
        ),
        migrations.CreateModel(
            name="RevisionArticleCollaboration",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "relation",
                    models.CharField(
                        choices=[
                            ("by", "by a collaboration"),
                            ("on_behalf_of", "on behalf of a collaboration"),
                            ("none", "No collaboration involved"),
                        ],
                        default="by",
                        help_text="Indicates whether the article was written by or on behalf of the collaboration",
                        max_length=32,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order of this collaboration in the author/collaboration list"
                    ),
                ),
                (
                    "collaboration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revision_storages",
                        to="wjs_submission.collaboration",
                    ),
                ),
                (
                    "revision_storage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collaborations",
                        to="wjs_submission.revisionstorage",
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
                "unique_together": {("revision_storage", "collaboration")},
            },
        ),
    ]
