# Generated by Django 4.2.25 on 2026-01-27 01:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wjs_submission", "0011_revisionarticleauthororder_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlesubmission",
            name="use_of_ai_flag",
            field=models.BooleanField(default=False, verbose_name="Use of AI"),
        ),
    ]
