# Generated by Django 4.2.25 on 2026-02-06 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wjs_submission", "0012_articlesubmission_use_of_ai_flag"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmissionArticleFunding",
            fields=[
                (
                    "articlefunding_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="submission.articlefunding",
                    ),
                ),
                ("country", models.CharField(blank=True, max_length=128)),
            ],
            bases=("submission.articlefunding",),
        ),
    ]
