# Generated by Django 4.2.25 on 2026-01-27 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wjs_submission", "0012_articlesubmission_use_of_ai_flag"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmissionArticleFunding",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("country", models.CharField(blank=True, max_length=128)),
                (
                    "article_funding",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submission_extra",
                        to="submission.articlefunding",
                    ),
                ),
            ],
        ),
    ]
