# Generated by Django 4.2.25 on 2026-02-07 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wjs_submission", "0013_submissionarticlefunding"),
    ]

    operations = [
        migrations.CreateModel(
            name="RevisionSubmissionArticleFunding",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Funder name", max_length=500)),
                (
                    "fundref_id",
                    models.CharField(
                        blank=True,
                        help_text="Funder DOI (optional). Enter as a full Uniform Resource Identifier (URI), such as https://dx.doi.org/10.13039/501100021082",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "funding_id",
                    models.CharField(
                        blank=True,
                        help_text="The grant ID (optional). Enter the ID by itself",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "funding_statement",
                    models.TextField(
                        blank=True,
                        help_text="Additional information regarding this funding entry",
                    ),
                ),
                ("country", models.CharField(blank=True, max_length=128)),
                (
                    "revision_storage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funding",
                        to="wjs_submission.revisionstorage",
                    ),
                ),
            ],
        ),
    ]
