# Generated by Django 4.2.25 on 2026-02-19 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wjs_submission", "0014_revisionsubmissionarticlefunding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="revisionsubmissionarticlefunding",
            name="funding_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The grant ID (optional). Enter the ID by itself",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="revisionsubmissionarticlefunding",
            name="fundref_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Funder DOI (optional). Enter as a full Uniform Resource Identifier (URI), such as https://dx.doi.org/10.13039/501100021082",
                max_length=500,
            ),
        ),
        migrations.CreateModel(
            name="WhitelistedCorrespondenceAuthors",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("validity_start_date", models.DateField(blank=True, null=True)),
                ("validity_stop_date", models.DateField(blank=True, null=True)),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="journal.journal",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Whitelisted correspondence author",
                "verbose_name_plural": "Whitelisted correspondence authors",
            },
        ),
    ]
