# Generated by Django 4.2.25 on 2026-03-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "wjs_submission",
            "0015_alter_revisionsubmissionarticlefunding_funding_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="articlesubmission",
            name="feedback_uuid",
            field=models.UUIDField(
                blank=True,
                help_text="Unique identifier for websocket feedback channel",
                null=True,
                verbose_name="Feedback UUID",
            ),
        ),
    ]
