# Generated by Django 4.2.25 on 2026-03-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wjs_submission", "0016_articlesubmission_feedback_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="revisionsubmissionarticlefunding",
            name="country",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="revisionsubmissionarticlefunding",
            name="funding_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The grant ID (optional). Enter the ID by itself",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="revisionsubmissionarticlefunding",
            name="funding_statement",
            field=models.TextField(
                blank=True,
                help_text="Additional information regarding this funding entry",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="revisionsubmissionarticlefunding",
            name="fundref_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Funder DOI (optional). Enter as a full Uniform Resource Identifier (URI), such as https://dx.doi.org/10.13039/501100021082",
                max_length=500,
                null=True,
            ),
        ),
    ]
