# Generated by Django 4.2.25 on 2026-03-17 12:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "wjs_submission",
            "0017_alter_revisionsubmissionarticlefunding_country_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="articlesubmission",
            name="administrative_files",
        ),
    ]
