# Generated by Django 4.2.22 on 2026-03-25 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wjs_submission", "0018_remove_articlesubmission_administrative_files"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="articlesubmission",
            name="affiliation_country",
        ),
        migrations.AddField(
            model_name="articlesubmission",
            name="affiliation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.controlledaffiliation",
                verbose_name="Affiliation",
            ),
        ),
    ]
