# Generated by Django 4.2.30 on 2026-07-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "wjs_submission",
            "0019_remove_articlesubmission_affiliation_country_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="articlesubmission",
            name="special_request_updated",
            field=models.BooleanField(
                default=False,
                verbose_name="Special request has been updated on revision",
            ),
        ),
    ]
