# Generated by Django 4.2.30 on 2026-05-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wjs_submission", "0019_remove_articlesubmission_affiliation_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlesubmission",
            name="cas",
            field=models.CharField(
                choices=[
                    ("no", "My article has no associated code or the code will not be deposited"),
                    ("esm", "My article has code included as electronic supplementary material"),
                    ("url", "My article has associated code in a repository"),
                ],
                default="",
                max_length=255,
                verbose_name="CAS declaration",
            ),
        ),
        migrations.AlterField(
            model_name="articlesubmission",
            name="das",
            field=models.CharField(
                choices=[
                    ("no", "My article has no associated data or the data will not be deposited"),
                    ("esm", "My article has data included as electronic supplementary material"),
                    ("url", "My article has associated data in a repository"),
                ],
                default="",
                max_length=255,
                verbose_name="DAS declaration",
            ),
        ),
    ]
