# Generated by Django 4.2.23 on 2026-07-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wjs_submission", "0020_articlesubmission_special_request_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlesubmission",
            name="license_override",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "If set, the EO has manually overridden the license. "
                    "Saving this ArticleSubmission will NOT auto-overwrite the article's "
                    "license from the AccessModeJournal configuration."
                ),
                verbose_name="License override",
            ),
        ),
        migrations.AddField(
            model_name="articlesubmission",
            name="rights_override",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "If set, the EO has manually overridden the copyright. "
                    "Saving this ArticleSubmission will NOT auto-overwrite the article's "
                    "rights from the AccessModeJournal configuration."
                ),
                verbose_name="Copyright override",
            ),
        ),
    ]
