# Generated by Django 4.2.29 on 2026-08-17 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0099_alter_accountrole_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wjs_submission", "0021_articlesubmission_license_override_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collaboration",
            name="short_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Abbreviated name, used in the text (e.g. ATLAS). If available",
                max_length=64,
                verbose_name="Short name",
            ),
        ),
        migrations.AddField(
            model_name="collaboration",
            name="logo_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Base name of the logo image file (e.g. CMS-collaboration-logo)",
                max_length=128,
                verbose_name="Logo name",
            ),
        ),
        migrations.AddField(
            model_name="collaboration",
            name="logo_size",
            field=models.CharField(
                blank=True,
                default="",
                help_text=(
                    "Graphicx options used to typeset the logo (e.g. width=1.8cm). Leave empty for the default size"
                ),
                max_length=64,
                verbose_name="Logo size",
            ),
        ),
        migrations.AddField(
            model_name="collaboration",
            name="moretex",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Additional LaTeX code to add to the papers of this collaboration (e.g. a \\paperNote{...})",
                verbose_name="Additional LaTeX",
            ),
        ),
        migrations.AddField(
            model_name="collaboration",
            name="author_list_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("regular", "Show full author list on front page (default)"),
                    ("corresponding", "List corresponding authors followed by et al."),
                    ("tagged", "List tagged authors followed by et al."),
                    ("first", "List first author followed by et al."),
                    ("empty", "Show no author list on front page"),
                    ("custom", "Use a custom author list text"),
                ],
                default="",
                help_text="How the front-page author list is abbreviated. Leave empty for the journal's default",
                max_length=32,
                verbose_name="Author list mode",
            ),
        ),
        migrations.AddField(
            model_name="collaboration",
            name="collaboration_list_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("regular", "Collaboration shown independently (default)"),
                    ("forthe", "Authors listed for the collaboration"),
                    ("behalf", "Authors listed on behalf of the collaboration"),
                    ("author", "Collaboration listed as additional author"),
                    ("empty", "Hide collaboration from front page"),
                ],
                default="",
                help_text=(
                    "How the collaboration name relates to the author list when typesetting. "
                    "Leave empty for the journal's default"
                ),
                max_length=32,
                verbose_name="Collaboration list mode",
            ),
        ),
        migrations.AddField(
            model_name="collaboration",
            name="cluster",
            field=models.BooleanField(
                default=False,
                help_text="If set, this collaboration has clusters of affiliations",
                verbose_name="Cluster",
            ),
        ),
        migrations.AddField(
            model_name="collaboration",
            name="sample_papers",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Manuscript IDs of papers to use as a typesetting reference (e.g. JCAP_114P_0326)",
                verbose_name="Sample papers",
            ),
        ),
        migrations.AlterField(
            model_name="collaboration",
            name="name",
            field=models.CharField(
                help_text="Full name, used in the metadata",
                max_length=255,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="collaboration",
            name="institutional_email",
            field=models.EmailField(
                blank=True,
                help_text="If available",
                max_length=254,
                verbose_name="Institutional email",
            ),
        ),
        migrations.AlterField(
            model_name="collaboration",
            name="logo",
            field=models.ForeignKey(
                blank=True,
                help_text="Logo representing this collaboration",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.file",
                verbose_name="Logo",
            ),
        ),
        migrations.AlterField(
            model_name="collaboration",
            name="address",
            field=models.TextField(blank=True, verbose_name="Address"),
        ),
        migrations.AlterField(
            model_name="collaboration",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Internal notes about how this collaboration must be handled",
                verbose_name="Notes",
            ),
        ),
        migrations.AlterField(
            model_name="collaboration",
            name="creator",
            field=models.ForeignKey(
                help_text="The account that created this collaboration",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_collaborations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AlterField(
            model_name="collaboration",
            name="linked_account",
            field=models.ForeignKey(
                blank=True,
                help_text="The account automatically added to the authors list when a collaboration is added",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_collaborations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Linked account",
            ),
        ),
    ]
