# Generated by Django 4.2.30 on 2026-09-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "wjs_submission",
            "0022_collaboration_author_list_mode_collaboration_cluster_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="articlesubmission",
            name="special_request_updated",
        ),
        migrations.AlterField(
            model_name="articlesubmission",
            name="license_override",
            field=models.BooleanField(
                default=False,
                help_text="If set, the article license is not auto-overwritten from the access mode configuration.",
                verbose_name="License override",
            ),
        ),
        migrations.AlterField(
            model_name="articlesubmission",
            name="rights_override",
            field=models.BooleanField(
                default=False,
                help_text="If set, the article copyright is not auto-overwritten from the access mode configuration.",
                verbose_name="Copyright override",
            ),
        ),
        migrations.AlterField(
            model_name="collaboration",
            name="logo_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Base name of the logo image file in repo /production/ilmarinen (e.g. CMS-collaboration-logo)",  # noqa
                max_length=128,
                verbose_name="Logo name",
            ),
        ),
    ]
