from .views import RevisionStartConfirmView as RevisionStartConfirmView
from .views import RevisionStartFullView as RevisionStartFullView
from .views import RevisionStartMetadataView as RevisionStartMetadataView
